#server:
#  port: 8021
#spring:
#  application:
#    name: nacos-service-discovery
#  cloud:
#    nacos:
#      #      server-addr: 127.0.0.1:8848
#      server-addr: 101.43.34.244:8848
#      username: nacos
#      password: nacos
#      discovery:
#        username: nacos
#        password: nacos
#        namespace: public
userNameTest: cy1
