server:
  port: 8024
#spring:
#  profiles:
#    active: dev

#spring:
#  application:
#    name: test2service
#  cloud:
#    nacos:
##      server-addr:  ${NACOS-HOST:101.43.34.244}:${NACOS-PORT:8848}
#      server-addr:  ${NACOS-HOST:127.0.0.1}:${NACOS-PORT:8848}

