server:
  port: 8023
spring:
  application:
    name: feign-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr:  ${NACOS-HOST:101.43.34.244}:${NACOS-PORT:8848}
#      server-addr:  ${NACOS-HOST:127.0.0.1}:${NACOS-PORT:8848}
      discovery:
        username: nacos
        password: nacos
        namespace: public
    sentinel:
      transport:
        dashboard: ${NACOS-HOST:101.43.34.244}:8858
feign:
  sentinel:
    enabled: true