server:
  port: 8088
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      #      server-addr: 127.0.0.1:8848
      server-addr: 101.43.34.244:8848
      username: nacos
      password: nacos
      discovery:
        username: nacos
        password: nacos
        namespace: public
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true  # 使用服务发现路由
          lower-case-service-id: true  # 服务路由名小写
#          在路由前加上服务名来访问，会自动去掉服务名去找资源
      routes:
        - id: feign-service
#          uri: http://localhost:8023
          uri: lb://feign-service
          predicates:
            - Path=/feign/**
          filters:
            - StripPrefix=1
